//GET https://sanhujori.plusrnd.com/api/v1/account/queryExec?qparam=%7Buser%28userId%3A%22spidermen%22%29%7Bid%2CuserId%2CuserName%2Ctelephone%2Cbirthday%2CestimatedDueDate%2CfileId%2CsysCid%2CinvitationCode%2CfromInvitationCode%2CcustCode%2CcreateDt%2CupdateDt%7D%7D HTTP/1.1
//Cookie: mymam-auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InNwaWRlcm1lbiIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA0NzcxNzYsInJvbGVDb2RlIjoiIiwibmFtZSI6InpoYW5nd2VpIiwiY3VzdElkIjoiIiwiaWQiOjEsImV4cCI6MTc4MDU2MzU3NiwiaWF0IjoxNzgwNDc3MTc2LCJlbWFpbCI6IiIsImRlcHRDb2RlIjoiIn0.CL7kXhhvR5DV9wWRoIAOWtLDpiS8uXjWR1VMWq0sSQI
//cookie: mymam-auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InNwaWRlcm1lbiIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA0NzcxNzYsInJvbGVDb2RlIjoiIiwibmFtZSI6InpoYW5nd2VpIiwiY3VzdElkIjoiIiwiaWQiOjEsImV4cCI6MTc4MDU2MzU3NiwiaWF0IjoxNzgwNDc3MTc2LCJlbWFpbCI6IiIsImRlcHRDb2RlIjoiIn0.CL7kXhhvR5DV9wWRoIAOWtLDpiS8uXjWR1VMWq0sSQI
//Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InNwaWRlcm1lbiIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA0NzcxNzYsInJvbGVDb2RlIjoiIiwibmFtZSI6InpoYW5nd2VpIiwiY3VzdElkIjoiIiwiaWQiOjEsImV4cCI6MTc4MDU2MzU3NiwiaWF0IjoxNzgwNDc3MTc2LCJlbWFpbCI6IiIsImRlcHRDb2RlIjoiIn0.CL7kXhhvR5DV9wWRoIAOWtLDpiS8uXjWR1VMWq0sSQI
//mymam-auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InNwaWRlcm1lbiIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA0NzcxNzYsInJvbGVDb2RlIjoiIiwibmFtZSI6InpoYW5nd2VpIiwiY3VzdElkIjoiIiwiaWQiOjEsImV4cCI6MTc4MDU2MzU3NiwiaWF0IjoxNzgwNDc3MTc2LCJlbWFpbCI6IiIsImRlcHRDb2RlIjoiIn0.CL7kXhhvR5DV9wWRoIAOWtLDpiS8uXjWR1VMWq0sSQI


# GET https://sanhujori.plusrnd.com/api/v1/account/queryExec?qparam=%7Buser%28userId%3A%22super1%22%29%7Bid%2CuserId%2CuserName%2Ctelephone%2Cbirthday%2CestimatedDueDate%2CfileId%2CsysCid%2CinvitationCode%2CfromInvitationCode%2CcustCode%2CcreateDt%2CupdateDt%7D%7D HTTP/1.1
# Cookie: mymam-auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InN1cGVyMSIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA1NTY3MzEsInJvbGVDb2RlIjoiIiwibmFtZSI6IuW8oOmjniIsImN1c3RJZCI6IiIsImlkIjozLCJleHAiOjE3ODA2NDMxMzEsImlhdCI6MTc4MDU1NjczMSwiZW1haWwiOiIiLCJkZXB0Q29kZSI6IiJ9.wdGO6g_qiX-_NFjL-Ow9vlFs00WViCGAGGnFRzg7Joo
//I/flutter (23002): cookie: mymam-auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InN1cGVyMSIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA1NTY3MzEsInJvbGVDb2RlIjoiIiwibmFtZSI6IuW8oOmjniIsImN1c3RJZCI6IiIsImlkIjozLCJleHAiOjE3ODA2NDMxMzEsImlhdCI6MTc4MDU1NjczMSwiZW1haWwiOiIiLCJkZXB0Q29kZSI6IiJ9.wdGO6g_qiX-_NFjL-Ow9vlFs00WViCGAGGnFRzg7Joo
//I/flutter (23002): mymam-auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6InN1cGVyMSIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiIiwicHJvcHMiOnt9LCJuYmYiOjE3ODA1NTY3MzEsInJvbGVDb2RlIjoiIiwibmFtZSI6IuW8oOmjniIsImN1c3RJZCI6IiIsImlkIjozLCJleHAiOjE3ODA2NDMxMzEsImlhdCI6MTc4MDU1NjczMSwiZW1haWwiOiIiLCJkZXB0Q29kZSI6IiJ9.wdGO6g_qiX-_NFjL-Ow9vlFs00WViCGAGGnFRzg7Joo


# GET  http://sanhujori.plusrnd.com/api/v1/account/queryExec?qparam=%familyInvitationRecordid,maternalUserId,inviteeUserId,inviteUserName,birthDay,gender{code,name,ename},inviteCode,inviteePhone,shareFlag{code,name,ename},inviteStatus{code,name,ename},createTime,acceptTime,cancelTime,expireTime,updateTime}} HTTP/1.1
# Cookie: mymam-auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6IjVWX3NwaWRlciIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiMSIsInByb3BzIjp7fSwibmJmIjoxNzgxNjc3ODM2LCJyb2xlQ29kZSI6IiIsIm5hbWUiOiLnjovkupQiLCJjdXN0SWQiOiIiLCJpZCI6IjEiLCJleHAiOjE3ODE3NjQyMzYsImlhdCI6MTc4MTY3NzgzNiwiZW1haWwiOiIiLCJkZXB0Q29kZSI6IiJ9.JYWc98KPScVZCHjJkbbyM3YuQvori8eOvImwkeyVKjs

GET https://sanhujori.plusrnd.com/api/v1/account/queryExec?qparam=bindMaternalContract%7Bid%2CmaternalUserId%2CcontractId%2CresId%2Cgid%2Cpid%2Csdate%2Cedate%2Cperiod%2CcontractDoc%2CcfDate%2CctDate%2CsysCid%2Cidate%2CtotalMoney%2Cstatus%2CcurVer%2CcustomerCode%2CcustomerName%2Cbirth%2CcontractDate%2CroomId%2CroomNo%2CroomLevel%2CroomLevelName%2ConlineDocId%2CsignType%2CpayStatus%2CsignStatus%2CpayAccount%2CmobilePhone%2Cemail%2CpmSrv%2Cctype%2CsignReqUid%2CdiscAmt%2CsignName%2CsreqId%2Cmemo%2CrPaidAmt%2CaesthPaidAmt%2CretAmt%2CactivateDt%7D
Content-Type: application/json
Cookie: mymam-auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6IjVWX3NwaWRlciIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiMSIsInByb3BzIjp7fSwibmJmIjoxNzgyODk4OTA2LCJyb2xlQ29kZSI6IiIsIm5hbWUiOiLnjovkupQiLCJjdXN0SWQiOiIiLCJpZCI6IjEiLCJleHAiOjE3ODI5ODUzMDYsImlhdCI6MTc4Mjg5ODkwNiwiZW1haWwiOiIiLCJkZXB0Q29kZSI6IiJ9.LwAnqw8UQRqHGlzvr7bk9JjWO1WO54XWVarLngYuvUI;
mymam-auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbXBJZCI6IjVWX3NwaWRlciIsInZlciI6IjEiLCJpc0FkbWluIjpmYWxzZSwic3RvcmVJZCI6IiIsInJvbGVUeXBlIjoiMSIsInByb3BzIjp7fSwibmJmIjoxNzgyODk4OTA2LCJyb2xlQ29kZSI6IiIsIm5hbWUiOiLnjovkupQiLCJjdXN0SWQiOiIiLCJpZCI6IjEiLCJleHAiOjE3ODI5ODUzMDYsImlhdCI6MTc4Mjg5ODkwNiwiZW1haWwiOiIiLCJkZXB0Q29kZSI6IiJ9.LwAnqw8UQRqHGlzvr7bk9JjWO1WO54XWVarLngYuvUI